service: demo 
plugins:
  - serverless-secrets-plugin
provider:
  name: aws
  stage: dev
  apiKeys:
    - ${self:custom.secrets.SESSION_KEY} # you can hide it in a serverless variable 
  runtime: nodejs8.10
  #vpc configuration
  vpc: 
    securityGroupIds:
      - ${self:custom.secrets.securityGroupIds}
    subnetIds:
      - ${self:custom.secrets.subnetIds1}
      - ${self:custom.secrets.subnetIds2}
  
  region: eu-west-1
  apiName: demo 
  profile: EFDEV
  timeout: 60
  memorySize: 512


custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  demo:
    handler: handler.demo
    name: demo
    description: Demo function in serverless
    environment: # Function level environment variables
      SESSION_KEY: ${self:custom.secrets.SESSION_KEY}
      EMAIL_SERVICE_API_KEY: ${self:custom.secrets.EMAIL_SERVICE_API_KEY}

    events:
   #  - schedule: rate(5 minutes) #cloudwatch scheduler
     - http:  
         path: demo
         method: get
         cors: true
         private: true
